// <auto-generated />
namespace NearDuplicatesAnalysis.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Baseline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Baseline));
        
        string IMigrationMetadata.Id
        {
            get { return "202002262246481_Baseline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
